# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 454dc3007d6ec48576929de3e18b37c4d509374324ed0808616c2a7c4e49c3605e7d4050fe149f278788d2a7c9c2c951c389ae75a6af7dc2f09faf8ebd821618

test:
  secret_key_base: e1e30c49bbb81fcf1662b9f0761eab1151e96548bdc76fe33c89b88f7c8f1d16fff83f2e12cc1be9228ef0f0a1ca84552253491eeaa85ca9be3a7428f6b140bd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: 366ba38b8ca6567fa3366c8f9965044354c5dd14ffa94919f70645aad5d5b20e4b738f3139031a33018f01dc6c12fc98839db139944cbb62d7915eee5cf897ac
  